### ISSUE TITLE
Improve exception messages with table and column names

### ISSUE THREAD

**Issue by marionzr** [marionzr/Nzr.Orm#20]
When an exception occurs (due an using error), the exception raised doesn't provide useful information that helps to identify where is the problem.

at Nzr.Orm.Core.Extensions.StringExtensions.AddWordSeparator(String text, Char separator)

Was occurred due to an error on a table naming conversion, but what entity (table name)

**Comment by marionzr** [comment]
Another example is when giving incompatible values to the parameters. For the parameter State.Id (an int value) the developer provided the text "CA", which leads to the following error 

```
The conversion of the nvarchar value 'CA' overflowed an int column.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at Nzr.Orm.Core.Dao.DoExecuteQuery[T](String sql, Parameters parameters, Boolean rawQuery)
   at Nzr.Orm.Core.Dao.DoSelect[T](Where where, OrderBy orderBy)
```

**Comment by marionzr** [comment]
See https://github.com/marionzr/Nzr.Orm/issues/34 resolution.
https://github.com/marionzr/Nzr.Orm/commit/9ab71849184b557baacfd63d577e15930580b323
