### ISSUE TITLE
Error selecting double referenced entity in query

### ISSUE THREAD

**Issue by marionzr** [marionzr/Nzr.Orm#21]
Consider the following objects (Disregard modeling)

```
Address
- Id
- City
- State

City
- State
```

When selecting the Address, both Address and City has the same inner entity State. In this case the following error occurs:

```
'An item with the same key has already been added. Key: [dbo].state.name'
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.Add(KeyValuePair`2 keyValuePair)
   at Nzr.Orm.Core.Dao.GetColumns(IDictionary`2& columns, Type type, Boolean includeForeingKeys)
   at Nzr.Orm.Core.Dao.GetColumns(IDictionary`2& columns, Type type, Boolean includeForeingKeys)
   at Nzr.Orm.Core.Dao.GetColumns(IDictionary`2& columns, Type type, Boolean includeForeingKeys)
   at Nzr.Orm.Core.Dao.GetColumns(IDictionary`2& columns, Type type, Boolean includeForeingKeys)
   at Nzr.Orm.Core.Dao.BuildSelectSql(Type type, Where where, OrderBy orderBy)
   at Nzr.Orm.Core.Dao.DoSelect[T](Where where, OrderBy orderBy)
```

**Comment by marionzr** [comment]
https://github.com/marionzr/Nzr.Orm/commit/3347ebc8698c005526e00c9d699950b44a53fcc5
