### ISSUE TITLE
Add support to nullable types

### ISSUE THREAD

**Issue by marionzr** [marionzr/Nzr.Orm#22]
Error when instantiating an entity with nullable type.

```
System.InvalidCastException: 'Invalid cast from 'System.Int32' to 'System.Nullable`1[[System.Int32, System.Private.CoreLib, 
 Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.'
    at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at Nzr.Orm.Core.Dao.ReadValue(SqlDataReader reader, KeyValuePair`2 column)
   at Nzr.Orm.Core.Dao.CreateInstance(Type type, SqlDataReader reader)
   at Nzr.Orm.Core.Dao.DoExecuteQuery[T](String sql, Parameters parameters, Boolean rawQuery)
   at Nzr.Orm.Core.Dao.DoSelect[T](Where where, OrderBy orderBy)
```

**Comment by marionzr** [comment]
https://github.com/marionzr/Nzr.Orm/commit/68f13fc89759195efd9eb162b5b138e1ab002e41
