### ISSUE TITLE
Exception without better description that helps to solve the problem.

### ISSUE THREAD

**Issue by marionzr** [marionzr/Nzr.Orm#29]
at Nzr.Orm.Core.Dao.<>c.<GetColumns>b__107_0(PropertyInfo p)
   at System.Linq.Enumerable.WhereArrayIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Nzr.Orm.Core.Dao.GetColumns(IList`1& columns, Type type, Boolean includeForeingKeys)
   at Nzr.Orm.Core.Dao.GetNonAutoGeneratedColumns(Type type)
   at Nzr.Orm.Core.Dao.BuildInsertSql(Type type)
   at Nzr.Orm.Core.Dao.DoInsert(Object entity)

**Comment by marionzr** [comment]
Error occurs on private properties due the GetGetMethod().IsPublic verification in the Dao.Schema.cs, at `private void GetColumns(ref IList<KeyValuePair<string, PropertyInfo>> columns, Type type, bool includeForeingKeys = false)

**Comment by marionzr** [comment]
It was an internal error in the System.Linq classes due to a bug that was solved in v0.7.1. 
The method that raised the exception was changed to include the type under reflection to help the diagnostic.

**Comment by marionzr** [comment]
https://github.com/marionzr/Nzr.Orm/commit/9ab71849184b557baacfd63d577e15930580b323
